"""second migration.

Revision ID: 738ff6464152
Revises: c8d04f04dac0
Create Date: 2021-02-04 21:09:25.055868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738ff6464152'
down_revision = 'c8d04f04dac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advert', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'advert', type_='foreignkey')
    op.create_foreign_key(None, 'advert', 'user', ['user_id'], ['id'])
    op.drop_column('advert', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advert', sa.Column('owner_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'advert', type_='foreignkey')
    op.create_foreign_key(None, 'advert', 'user', ['owner_id'], ['id'])
    op.drop_column('advert', 'user_id')
    # ### end Alembic commands ###
